services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      - 'POSTGRES_DB=kardapio'
      - 'POSTGRES_PASSWORD=kardapio'
      - 'POSTGRES_USER=kardapio'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: