spring:
  datasource:
    username: kardapio
    password: kardapio
    url: jdbc:postgresql://${api.configs.database.host}:${api.configs.database.port}}/${api.configs.database.database_name}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 858555504557-h20bcel6tdpr1cjcgkauv23ielpq0kbn.apps.googleusercontent.com
            client-secret: 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
api:
  configs:
    database:
      host: localhost
      port: 5432
      database_name: kardapio
    security:
      token:
        secret: eusouumsegredo

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
