spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kardapio
    username: kardapio
    password: kardapio
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

api:
  configs:
    security:
      token:
        secret: seu_valor_secreto_aqui

