spring:
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${api.configs.database.host}:${api.configs.database.port}}/${api.configs.database.database_name}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}}
            client-secret: ${GOOGLE_CLIENT_SECRET}}
logging:
  level:
    org:
      springframework:
        security: DEBUG
api:
  configs:
    database:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      database_name: ${DATABASE_NAME}
    security:
      token:
        secret: ${JWT_SECRET}

apis:
  viacep:
    url: https://viacep.com.br/ws/


