spring:
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${api.configs.database.host}:${api.configs.database.port}/${api.configs.database.database_name}
    hikari:
      maximum-pool-size: 10
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}}
            client-secret: ${GOOGLE_CLIENT_SECRET}}
api:
  configs:
    database:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      database_name: ${DATABASE_NAME}
    server:
      port: 8080
    security:
      token:
        secret: ${JWT_SECRET}
