CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "user_role" AS ENUM (
    'Consumer',
    'Owner',
    'Employee',
    'DeliveryMan',
    'Admin'
    );

CREATE TYPE "account_provider" AS ENUM (
    'Google',
    'Apple',
    'Meta'
    );

CREATE TYPE "cousine_type" AS ENUM (
    'ITALIANA',
    'FRANCESA',
    'JAPONESA',
    'PORTUGUESA',
    'MEXICANA',
    'ARABE',
    'BRASILEIRA',
    'TAILANDESA',
    'DOCES',
    'SALGADOS'
    );

CREATE TYPE "order_status" AS ENUM (
    'CREATED',
    'IN_PROGRESS',
    'FINISHED',
    'CANCELED'
    );

CREATE TYPE "weekday" AS ENUM (
    'MONDAY',
    'TUESDAY',
    'WEDNESDAY',
    'THURSDAY',
    'FRIDAY',
    'SATURDAY',
    'SUNDAY'
    );

CREATE TABLE "users" (
                         "id" UUID DEFAULT uuid_generate_v4() UNIQUE PRIMARY KEY NOT NULL,
                         "profile_id" integer,
                         "email" varchar UNIQUE NOT NULL,
                         "password" varchar(50),
                         "role" user_role,
                         "account_provider" account_provider,
                         "created_at" TIMESTAMPTZ,
                         "updated_at" TIMESTAMPTZ
);

CREATE TABLE "profile" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                           "name" varchar(25) NOT NULL,
                           "last_name" varchar(75) NOT NULL,
                           "cpf" varchar(11) UNIQUE NOT NULL,
                           "phone" varchar(14) NOT NULL,
                           "created_at" TIMESTAMPTZ,
                           "updated_at" TIMESTAMPTZ
);

CREATE TABLE "address" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                           "profile_id" integer,
                           "street" varchar NOT NULL,
                           "number" varchar NOT NULL,
                           "complement" varchar NOT NULL,
                           "district" varchar NOT NULL,
                           "cep" varchar NOT NULL,
                           "city" varchar NOT NULL,
                           "state" varchar NOT NULL,
                           "created_at" TIMESTAMPTZ,
                           "updated_at" TIMESTAMPTZ
);

CREATE TABLE "owner" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "users_id" UUID,
                         "restaurant_id" integer,
                         "created_at" TIMESTAMPTZ,
                         "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "employee" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                            "users_id" UUID,
                            "created_at" TIMESTAMPTZ,
                            "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "employee_restaurant" (
                                       "employee_id" integer,
                                       "restaurant_id" integer
);

CREATE TABLE "restaurant" (
                              "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                              "name" varchar NOT NULL,
                              "cnpj" varchar UNIQUE NOT NULL,
                              "phone" varchar UNIQUE NOT NULL,
                              "score" decimal(4,2),
                              "address_id" integer,
                              "created_at" TIMESTAMPTZ,
                              "updated_at" TIMESTAMPTZ,
                              "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "restaurants_cousineType" (
                                           "restaurant_id" integer,
                                           "cousine_type_id" integer
);

CREATE TABLE "cousineType" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                               "name" cousine_type
);

CREATE TABLE "order" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "profile_id" integer,
                         "shipping_value" decimal(4,2),
                         "total_value" decimal(4,2),
                         "status" order_status,
                         "created_at" TIMESTAMPTZ,
                         "updated_at" TIMESTAMPTZ,
                         "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "orders_items" (
                                "order_id" integer,
                                "item_id" integer
);

CREATE TABLE "item" (
                        "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                        "restaurant_id" integer,
                        "name" varchar,
                        "description" varchar,
                        "img" varchar,
                        "value" decimal(4,2),
                        "score" decimal(3,2),
                        "created_at" TIMESTAMPTZ,
                        "updated_at" TIMESTAMPTZ,
                        "deleted_at" TIMESTAMPTZ
);

CREATE TABLE "paymentMethod" (
                                 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                                 "name" varchar,
                                 "description" varchar,
                                 "isOnline" boolean
);

CREATE TABLE "businessHours" (
                                 "restaurant_id" integer,
                                 "weekday" weekday,
                                 "opening_time" TIME,
                                 "closing_time" TIME
);

CREATE TABLE "restaurants_paymentMethods" (
                                              "paymentMethod_id" integer,
                                              "restaurant_id" integer
);

CREATE TABLE "profile_restaurants" (
                                       "users_id" UUID,
                                       "restaurante_id" integer
);

ALTER TABLE "users" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "address" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "owner" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "owner" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");

ALTER TABLE "employee" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "employee_restaurant" ADD FOREIGN KEY ("employee_id") REFERENCES "employee" ("id");

ALTER TABLE "employee_restaurant" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");

ALTER TABLE "restaurant" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "restaurants_cousineType" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");

ALTER TABLE "restaurants_cousineType" ADD FOREIGN KEY ("cousine_type_id") REFERENCES "cousineType" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "orders_items" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "orders_items" ADD FOREIGN KEY ("item_id") REFERENCES "item" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");

ALTER TABLE "businessHours" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");

ALTER TABLE "restaurants_paymentMethods" ADD FOREIGN KEY ("paymentMethod_id") REFERENCES "paymentMethod" ("id");

ALTER TABLE "restaurants_paymentMethods" ADD FOREIGN KEY ("restaurant_id") REFERENCES "restaurant" ("id");
